Fix "Invalid format string" in Windows
ValueError: Invalid format string

%l is not standard: %l - Hour of the day, 12-hour clock, blank-padded ( 1..12)

The Windows implementations doesn't support it:
https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx
https://docs.python.org/3/library/time.html

Use %I instead: %I - Hour of the day, 12-hour clock, zero-padded (01..12)